#!/bin/bash
#cmake .. -GXcode \
ARCH=arm64
SDK=iphoneos
cmake .. -GNinja \
 -DCMAKE_SYSTEM_NAME=iOS \
 -DCMAKE_OSX_SYSROOT=$SDK \
 -DCMAKE_C_COMPILER=clang  \
 -DCMAKE_CXX_COMPILER=clang++ \
 -DCMAKE_OSX_ARCHITECTURES=$ARCH \
 -DCMAKE_BUILD_TYPE=Release \
 -DTBB_INSTALL_TARGETS=ON \
 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.0 \
 -DTBB_BUILD_TESTS=OFF \
 -DCMAKE_INSTALL_PREFIX=/Users/pt/Github/tbb/install/ios/$ARCH
